ALTER TABLE admin CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ps CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE pt CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE student CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE subject CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE subject_required CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE term CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;